channels:
- conda-forge
- defaults
- bioconda
dependencies:
- r-rhandsontable
- r-shinyjs
- r-RColorBrewer
- r-ggrastr
- r-dplyr
- r-readr
- bioconductor-debrowser
- r-rclipboard
- r-vegan
- r-DT
- r-NMF
- r-rspectra
- r-markdown
- bioconductor-dada2
- r-dt
- bioconductor-motifdb
- bioconductor-sva
- bioconductor-enhancedvolcano
- r-shinydashboard
- r-lme4
- r-nloptr
- r-vennDiagram
- r-shinycssloaders
- r-ggpubr
- r-uwot
- bioconductor-batchelor
- r-ggplot2
- bioconductor-complexheatmap
- bioconductor-summarizedexperiment
- r-sodium
- r-heatmaply
- bioconductor-deseq2
- bioconductor-pathview
- r-devtools
- r-shiny
- r-magrittr
- r-ggthemes
- bioconductor-clusterprofiler
- bioconductor-genomicalignments
- bioconductor-glmgampoi
- presto
- r-uuid
- bioconductor-delayedmatrixstats
- bioconductor-limma
- r-reticulate
- r-stringr
- bpp-core
- bioconductor-singlecellexperiment
- r-rstatix
- r-shinyBS
- biom-format
- bioconductor-multiassayexperiment
- bioconductor-interactivecomplexheatmap
- bioconductor-biocgenerics
- bioconductor-hdf5array
- bioconductor-delayedarray
- bioconductor-animalcules
- bioconductor-atacseqqc
- bioconductor-chippeakanno
- r-plotly
- r-v8
- r-base==4.3.3
- bioconductor-s4vectors
- r-future
- r-terra
- r-car
name: merged_env
