channels:
- bioconda
- defaults
- conda-forge
dependencies:
- r-ggthemes
- r-plotly
- r-DT
- r-nloptr
- r-dplyr
- r-v8
- bioconductor-s4vectors
- bioconductor-limmagui
- r-ggplot2
- r-clustree
- r-rspectra
- r-shinyBS
- r-vegan
- r-devtools
- r-sodium
- r-heatmaply
- bioconductor-delayedmatrixstats
- r-reticulate
- r-readr
- bioconductor-enhancedvolcano
- bioconductor-batchelor
- r-shiny
- bpp-core
- bioconductor-limma
- r-reshape2
- r-uwot
- bioconductor-atacseqqc
- biom-format
- bioconductor-chippeakanno
- bioconductor-multiassayexperiment
- r-rstatix
- r-ggpubr
- r-RColorBrewer
- bioconductor-biocgenerics
- bioconductor-summarizedexperiment
- bioconductor-clusterprofiler
- bioconductor-glmgampoi
- bioconductor-deseq2
- r-pheatmap
- bioconductor-sva
- r-uuid
- r-vennDiagram
- r-ggrastr
- r-shinyjs
- bioconductor-delayedarray
- bioconductor-hdf5array
- bioconductor-interactivecomplexheatmap
- bioconductor-edger
- r-lme4
- r-NMF
- r-stringr
- bioconductor-complexheatmap
- bioconductor-genomicalignments
- bioconductor-dada2
- r-base==4.3.3
- r-rhandsontable
- r-shinycssloaders
- bioconductor-motifdb
- r-rclipboard
- r-dt
- r-shinydashboard
- bioconductor-animalcules
- r-markdown
- presto
- bioconductor-pathview
- r-terra
- r-tidyr
- r-magrittr
- bioconductor-debrowser
- bioconductor-singlecellexperiment
- r-car
- r-gplots
- r-ggvis
- r-ggrepel
- r-future
name: merged_env
